### ISSUE TITLE
Readme totally destroyed my ability to use xrdp from Win11 to remote desktop in Linux Mint server

### ISSUE THREAD

**Issue by cantcurecancer** [Kimi450/ubuntu_server#20]

**Comment by Kimi450** [comment]
I'm not sure what you mean. It is always recommended to go through the code to see what is going to run before you run it too.

**Comment by cantcurecancer** [comment]
Sorry, ignore this comment. Your readme was not responsible for my issues. I was actually attempting to connect to the wrong server and I'm only now realizing this. Thanks for your guide.

**Comment by Kimi450** [comment]
No worries, good luck.
